### PR TITLE
Byte messages

### PR DESCRIPTION
**Pull request by BlueNZ**
A first optimization of sent messages in order to minimize their size. 

Request are now formatted as :
 **KEY - COMMAND - PARAMETERS - CONTINUE - OTHER_COMMANDS - END** 

with **KEY** a predetermined sequence of bytes to ensure the message is a formatted one

with **COMMAND** being one byte:

- CONNECT : \x01
- INPUT : \x02
- DISCONNECTION : \x03
- CONNECTED : \x0a
- STATE : \x0b
- WALLS : \x0c
- SHADES : \x0d
- LOBBY : \x0e
- TRANSITION_GAME_LOBBY : \x0f
- TRANSITION_LOBBY_GAME : \x10
- GAME : \x11
- DISCONNECTED : \x12
- ERROR : \x14

with **PARAMETERS** a sequence of **PARAMETER - VARIABLE**
a **PARAMETER** is encoded with a type byte and its value or variables :

 - int : \x01 + value (encoded without null bytes)
 - float : \x02 + value * FLOAT_PRECISION encoded as an int
 - string : \x03 + value encoded in utf-8
 - boolean : \x04 + (value as a byte +1)
 - list : \x0a + (nbr of elements+1) + elements encoded
 - tuple : \x0b + (nbr of elements+1) + elements encoded
 - Player : \x14 + parameters encoded
 - Wall : \x15 + parameters encoded
 - Color : \x1e + r g and b encoded as ints
 - Position : \x1f + x and y encoded as ints
 - Size : \x20 + w and h encoded as ints

FLOAT_PRECISION is a constant (currently 10 for a one digit precision)

**VARIABLE**, **CONTINUE** and **END** are special sequence of bytes used for semantics (respectively \x00, \x00\x00 and \x00\x00\x00)

**Example:**
What was:
`"CONNECTED John (500,500) WALLS [(0,(20,20,20),(10,10),(100,10))] LOBBY [] STATE [(0,John,(255,0,0),(50,50),(20,20))] END"`
Is now: 
`["CONNECTED", "John", (500,500), "WALLS", [Wall(0,Color(20,20,20),Position(10,10),Size(100,10))], "LOBBY", [], "STATE", [Player(0,"John",Color(255,0,0),Position(50,50),Size(20,20))], "END"]`
Encoded as (without the KEY): 
`b'\x0a\x03\x4a\x6f\x68\x6e\x00\x0b\x03\x01\x02\xf6\x00\x01\x02\x6f\x00\x00\x0c\x0a\x02\x15\x01\x00\x15\x00\x15\x00\x15\x00\x0b\x00\x0b\x00\x65\x00\x0b\x00\x00\x0e\x0a\x01\x00\x00\x0b\x0a\x02\x14\x01\x00\x4a\x6f\x68\x6e\x00\x02\x01\x00\x01\x00\x01\x00\x33\x00\x33\x00\x15\x00\x15\x00\x00\x00'`
And decoded as:
`[["CONNECTED", "John", (500,500), "END"], ["WALLS", [Wall(0,Color(20,20,20),Position(10,10),Size(100,10))], "END"], ["LOBBY", [], "END"],  ["STATE", [Player(0,"John",Color(255,0,0),Position(50,50),Size(20,20))], "END"]]`

In this example the old way took 120 bytes while the new way takes 82 bytes with the KEY

As a bonus, strings now can include any sort of characters such as spaces, parenthesis or brackets...

### CODE REVIEW

**Comment by ZynoXelek** [comment]
Incredible work! Well done!

Didn't check all the code, I may ask you how some things work next week but your description is really clean and it looks awesome!

**Comment by BlueNZ** [comment]
With a few tests it does not seem to minimize messages length, on the contrary

**Comment by BlueNZ** [comment]
After some 'bidouillage' it is now an improvement.

However in practice since an int is now encoded with at least 2 bytes while a char such as '0' is encoded on one, and since the shadow polygon sent encompass a lot of (seemingly useless) points on the border (so (x,0) or (0,y)) it does not gain much.

It might be wise to try and get rid of all those 'useless' points.

**Comment by BlueNZ** [comment]
Does not work out of local

**Pull request closed without merging**
